### ISSUE TITLE
When radios or checkboxes are greater than the standard length the right padding should be 1rem from the label.

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/pattern-library-v2#207]
When radios or checkboxes are greater than the standard length the right padding should be 1rem from the label.

_Originally posted by @will-madebymoon in https://github.com/ONSdigital/pattern-library-v2/issues/56#issuecomment-465548500_

**Comment by bameyrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #207: When radios or checkboxes are greater than the standard length the right padding should be 1rem from the label.](https://trello.com/c/uf1C4cwb/166-issue-207-when-radios-or-checkboxes-are-greater-than-the-standard-length-the-right-padding-should-be-1rem-from-the-label)
